### PR TITLE
Update liferay archetype #8833

### PR DESCRIPTION
**Pull request by mmerruko**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/archetypes/128)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[vaadin-archetype-liferay-portlet/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhRZ4EaPNPqylcNUdHv:-KhRZ4EaPNPqylcNUdHw:bdgjbiz) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/pom.xml#L25)):*
> ```XML
>         the Vaadin bundles being installed on the portal server.
>         
>         This example builds an OSGi bundle that can be installed on a Liferay server. 
> ```

example? an archetype should be not an example but project skeleton

---

*[vaadin-archetype-liferay-portlet/README.MD, line 4 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhRZZ1EGO3b9HEat2WO:-KhRZZ1EGO3b9HEat2WP:b-wu0qez) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/README.MD#L4)):*
> ```
> This archetype generates a Liferay portlet plugin project that relies on the Vaadin bundles being installed on the portal server.
> ## Maven profile
> This example builds an OSGi bundle that can be installed on a Liferay server. The Vaadin integration handles the registration of the annotated UI as a Portet. 
> ```

example again

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/bnd.bnd, line 5 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhRZfyX_hBNC7op64kr:-KhRZfyYFcP2zepryx0g:b-1kxde5) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/bnd.bnd#L5)):*
> ```
> Bundle-SymbolicName: \${symbol_dollar}{project.groupId}.\${symbol_dollar}{project.artifactId}
> Export-Package: ${package}
> Import-Package: !com.google*,\
> ```

without dot?

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/bnd.bnd, line 8 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhRZeMzQQKebRqMW8f-:-KhRZeN-E_LKHzf03Nbx:b-k10qpq) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/bnd.bnd#L8)):*
> ```
>     !com.vaadin.client*,\
>     *
>     
> ```

extra spaces

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml, line 193 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhR_7LFHSJU8MLs7Ymm:-KhR_7LGFFzeWi5N9yHg:bbfdfb8) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml#L193)):*
> ```XML
> 						<configuration>
> 							
> 							
> ```

looks like example code gain

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/128)*

**Comment by mmerruko** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-archetype-liferay-portlet/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhRZ4EaPNPqylcNUdHv:-KhSBbE2ty2-mtGHs5Nb:b-896fix) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/pom.xml#L25)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

example? an archetype should be not an example but project skeleton
</blockquote></details>

Done.

---

*[vaadin-archetype-liferay-portlet/README.MD, line 4 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhRZZ1EGO3b9HEat2WO:-KhSBajYDw6WKIjuy71v:b-896fix) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/README.MD#L4)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

example again
</blockquote></details>

Done.

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/bnd.bnd, line 5 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhRZfyX_hBNC7op64kr:-KhSBTomlCzqd5ipAG5C:b-rszzoy) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/bnd.bnd#L5)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

without dot?
</blockquote></details>

This is intentional, it covers the root package as well `com.vaadin.client` and all subpackages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/128)*

**Comment by mmerruko** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml, line 193 at r1](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KhR_7LFHSJU8MLs7Ymm:-KhSBktYOAN6jOeeebDh:bss4a2b) ([raw file](https://github.com/vaadin/archetypes/blob/c88d21c3d78df7bfd5c70b94f3da2aa0613105b8/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml#L193)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

looks like example code gain
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/128)*

**Comment by elmot** [comment]
Reviewed 10 of 14 files at r1, 2 of 4 files at r2.
Review status: 12 of 14 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[vaadin-archetype-liferay-portlet/pom.xml, line 1 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KiehgFZ_BsNNyLepFrD:-KiehgF_6PPrU7yYgykn:bfbxvoj) ([raw file](https://github.com/vaadin/archetypes/blob/a83e7df3abeafea80487d7941ea6bfd7ec6a1730/vaadin-archetype-liferay-portlet/pom.xml#L1)):*
> ```XML
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> ```

Standard xml header is missing
`<?xml version="1.0" encoding="UTF-8"?>`

---

*[vaadin-archetype-liferay-portlet/pom.xml, line 4 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KiehpHM6dhAfiZvp64j:-KiehpHM6dhAfiZvp64k:b-4t61ab) ([raw file](https://github.com/vaadin/archetypes/blob/a83e7df3abeafea80487d7941ea6bfd7ec6a1730/vaadin-archetype-liferay-portlet/pom.xml#L4)):*
> 1
looks like 3 is the very last version

---

*[vaadin-archetype-liferay-portlet/pom.xml, line 4 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KieiEp6y-LDRR0b6Dpu:-KieiEp6y-LDRR0b6Dpv:b-8dwz74) ([raw file](https://github.com/vaadin/archetypes/blob/a83e7df3abeafea80487d7941ea6bfd7ec6a1730/vaadin-archetype-liferay-portlet/pom.xml#L4)):*
> 0
1

---

*[vaadin-archetype-liferay-portlet/pom.xml, line 9 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KiejDGFLS33_n45MTaO:-KiejDGG15vitB53lLGL:bxhvx8s) ([raw file](https://github.com/vaadin/archetypes/blob/a83e7df3abeafea80487d7941ea6bfd7ec6a1730/vaadin-archetype-liferay-portlet/pom.xml#L9)):*
> 8.0
8.1 must be here and everywhere in the project

---

*[vaadin-archetype-liferay-portlet/pom.xml, line 24 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KiegwitLKJAePsUnVRI:-KiegwitLKJAePsUnVRJ:baun0cp) ([raw file](https://github.com/vaadin/archetypes/blob/a83e7df3abeafea80487d7941ea6bfd7ec6a1730/vaadin-archetype-liferay-portlet/pom.xml#L24)):*
> Liferay
Liferay 7+

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml, line 1 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/128#-KiehHGiSQNk5sp2G2-o:-KiehHGiSQNk5sp2G2-p:b21o0wi) ([raw file](https://github.com/vaadin/archetypes/blob/a83e7df3abeafea80487d7941ea6bfd7ec6a1730/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml#L1)):*
> ```XML
> 
> ```

Extra empty line. It breaks the whole project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/128)*

**Comment by elmot** [comment]
Done with #129

**Pull request closed without merging**
