### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by mstahv**
Updated to a more modern and supported Java version

### CODE REVIEW

**Review by samie — APPROVED** [review]

**Comment by manolo** [comment]
shouldn't it be java 11 and also target to both archetypes ?

**Comment by mstahv** [comment]
I think it should be the latest Java LTS (17), but at least it should not be a version that don't work with Vaadin anymore. Probably for all archetypes, not sure if they are involved.

**Comment by mstahv** [comment]
Now the other archetype also defaults to Java 17

**Comment by tarekoraby** [comment]
IMO we should default to java 11 until we have solid proof that the majority of Java users out there have 17 already installed.

**Comment by mstahv** [comment]
Don't know why we should do it differently in archetypes then we do it in start.vaadin.com and how Spring people are doing it in Spring Initializr. But I do agree the example code we provide in the archetype should be Java 11 compatible until people using that becomes a small subset of our users, not just minority.

**Comment by mstahv** [comment]
A good reason to make the default Java 11, would be that our CI server seems to try building this with JDK 11, which naturally fails 🤓

@manolo Do you know if we can easily change the archetypes to be built with JDK 17?

**Comment by ZheSun88** [comment]
the validation build failed as there is no prerelease repo configured in the generated archetype, for fixing the build, we should update the generated project pom to [include those](https://github.com/vaadin/archetypes/blob/master/vaadin-archetype-application/src/main/resources/archetype-resources/pom.xml#L18), but those settings are not useful to our users, as we should no suggest them to use our snapshots (or do we?)  and even for now, we don't release archetypes for prereleases. And the main idea was to be sure that the generated project pom is as simply as it can be.. 

so in this case.. **this archetypes validation build should be dropped**, just like it is shown here, as it is not required before merging the PR.  

and one more thing related to the changes here, as the java version has been upgraded to 17, remember to update the release build to use java 17 too.

**Comment by mstahv** [comment]
If it gets too complicated, I'm fine to getting back to Java 11 as default, Java 17 would just be better in line with other ways to get started. For end users, it is easy to change it for anything they like.

BTW. Could we have the pre-release repository in settings.xml in the CI server? This way we could build verification build against the snapshot builds, but avoid having the extra repositories configured.

**Comment by ZheSun88** [comment]
>BTW. Could we have the pre-release repository in settings.xml in the CI server? 

this sounds like a good idea.. let me check. if it is working in this way.

**Comment by mstahv** [comment]
Like a pro @ZheSun88, looks good to me now💪

**Comment by ZheSun88** [comment]
now, the issue has been fixed and test has been successfully run.

so the main thing here, is 
- the `<archetype.test.settingsFile>` parameter. 
- the setting file
  - when uploading the file to teamcity, the file will be interpolated to a name which is only readable by TC, like something `/opt/agent/temp/buildTmp/maven_settings_1649192949527213774.xml` . so let us keep in the repo, as there is no sensitive info inside. 
  - the profile in the settings file needs a separate trigger to turn it on, so i use the <id>, test. (i dont like the activeBydefault, as it is not clear to when doing investigations)

**Comment by mstahv** [comment]
Will this PR get better like wine here 🤓 My next batch of improvements in https://github.com/vaadin/archetypes/pull/195  would need the changes for the validation built to pass.

**Comment by ZheSun88** [comment]
I thought someone else will review it.. now, let us merge it.. we can fix, if something is wrong.

**Pull request merged**
