### PR TITLE
Vaadin 8.1 + Liferay 7 archetype

### PR DESCRIPTION
**Pull request by elmot**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/archetypes/129)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 10 of 14 files at r1, 10 of 11 files at r2.
Review status: 20 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[pom.xml, line 12 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii2GE7Flg4JodlAGDi:-Kii2GE7Flg4JodlAGDj:b-qrj8ul) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/pom.xml#L12)):*
> ```XML
>   <groupId>com.vaadin</groupId>
>   <artifactId>vaadin-archetypes</artifactId>
>   <version>8.1-SNAPSHOT</version>
> ```

this (and some of the changes below) affects more than just this archetype, and needs to be coordinated with changes in CI configurations and branches for the repo - I'll take a look at this later

---

*[vaadin-archetype-liferay-portlet-sharedlib/pom.xml, line 9 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii2o-3b0b2wz0OYFuh:-Kii2o-4Kg8crik4O1KU:b8h3meo) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet-sharedlib/pom.xml#L9)):*
> ```XML
> 		<version>8.1-SNAPSHOT</version>
> 	</parent>
> 	<name>Vaadin 7 Liferay 6 archetype</name>
> ```

Vaadin 8

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml, line 136 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii3cEt-ewvuCuTVTc6:-Kii3cEt-ewvuCuTVTc7:brjxv34) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml#L136)):*
> ```XML
> 				<artifactId>maven-resources-plugin</artifactId>
> 				<version>2.6</version>
> 				<executions>
> ```

(it feels a bit strange that we need this and the resources conf above is not sufficient, but ok if we need this)

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/__theme__.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii3wJhxCsO81Sp57xw:-Kii3wJhxCsO81Sp57xx:bs16kfs) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/__theme__.java#L9)):*
> ```Java
> 
> @Component(immediate = true, service = OSGiVaadinTheme.class)
> public class ${theme} extends ValoTheme implements OSGiVaadinTheme {
> ```

this will lead to unconventional class or theme names (capitalization) - I wonder if a fixed class name would be better

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/__uiClassName__.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii4AFdO-zuJN5AAdNf:-Kii4AFeFGkzV0UrtDfk:b-bb8gzv) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/__uiClassName__.java#L28)):*
> ```Java
> @SuppressWarnings("serial")
> @Widgetset("${package}.AppWidgetSet")
> @Component(service = UI.class, property = {
> ```

(ok, but wondering why not using the other approach with @VaadinLiferayPortletConfiguration and the related dependency)

---

*[vaadin-archetype-liferay-portlet/src/main/resources/META-INF/maven/archetype-metadata.xml, line 62 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii4lc0z9Y5rM_rxGRG:-Kii4lc0z9Y5rM_rxGRH:b-i2mnt4) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/META-INF/maven/archetype-metadata.xml#L62)):*
> ```XML
> 			</includes>
> 		</fileSet>
> 		<fileSet filtered="true" encoding="UTF-8">
> ```

does this filtering setting override the filtered=false block below now that there are no explicit includes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/129)*

**Comment by hesara** [comment]
Reviewed 1 of 14 files at r1, 1 of 11 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/129)*

**Comment by elmot** [comment]
Review status: 18 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-archetype-liferay-portlet-sharedlib/pom.xml, line 9 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii2o-3b0b2wz0OYFuh:-Kii5uhlIZ4G5TAWWF0H:b-896fix) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet-sharedlib/pom.xml#L9)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

Vaadin 8
</blockquote></details>

Done.

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml, line 136 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii3cEt-ewvuCuTVTc6:-KiiS-ozoRVVneZHQlD5:ba3dfob) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml#L136)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(it feels a bit strange that we need this and the resources conf above is not sufficient, but ok if we need this)
</blockquote></details>

Removed

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/__uiClassName__.java, line 28 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii4AFdO-zuJN5AAdNf:-KiiS93lV-V2DDFt52nb:b4rfjnn) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/__uiClassName__.java#L28)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

(ok, but wondering why not using the other approach with @VaadinLiferayPortletConfiguration and the related dependency)
</blockquote></details>

That looks like an example of alternate approach. We can leave that here or change to vaadin annotation

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/AppTheme.java, line 9 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii3wJhxCsO81Sp57xw:-KiiRoKigYPI3JS7novr:b-ms6sv) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/src/main/java/AppTheme.java#L9)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

this will lead to unconventional class or theme names (capitalization) - I wonder if a fixed class name would be better
</blockquote></details>

Done. Changed to static name.

---

*[vaadin-archetype-liferay-portlet/src/main/resources/META-INF/maven/archetype-metadata.xml, line 62 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii4lc0z9Y5rM_rxGRG:-KiiRd3-XZe5Les1erSc:b-jmwouv) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/META-INF/maven/archetype-metadata.xml#L62)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary><blockquote>

does this filtering setting override the filtered=false block below now that there are no explicit includes?
</blockquote></details>

Good catch. That effectively broke the icon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/129)*

**Comment by hesara** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml, line 136 at r2](https://reviewable.io:443/reviews/vaadin/archetypes/129#-Kii3cEt-ewvuCuTVTc6:-KiiUE79YvukLNJLUyeg:b-mjmq9o) ([raw file](https://github.com/vaadin/archetypes/blob/1dcbabde5d31c91375cb234f1438db6ee2cba545/vaadin-archetype-liferay-portlet/src/main/resources/archetype-resources/pom.xml#L136)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

@mmerruko  any comment on this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/129)*

**Comment by mmerruko** [comment]
:lgtm:

---

Reviewed 9 of 15 files at r1, 9 of 11 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/129#-:-Kij1Ihl-JrETVBxqn93:bnfp4nl)*

**Pull request merged**
