### PR TITLE
Parent pom and correct version for 7.7

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/archetypes/1)

### CODE REVIEW

**Comment by pleku** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/archetypes/1#-KTx_qRdClb3O4GTk0fn:-KTx_qRdClb3O4GTk0fo:b-v8kui7) (no related file):*
If the versions are bound together currently, why is there not a single version property used, e.g. set in the parent pom and then used in sub modules ? With value 7.7-SNAPSHOT ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/1)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/archetypes/1#-KTx_qRdClb3O4GTk0fn:-KTxlQZMpHPgNhAPU-Fz:b-bdr05r) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>
> If the versions are bound together currently, why is there not a single version property used, e.g. set in the parent pom and then used in sub modules ? With value 7.7-SNAPSHOT ?
</details>
Where would you use that property? To define the parent artifact using a variable which comes from the parent artifact? The `<version>` tags in the poms are probably unnecessary but they need to refer to the parent POM using `7.7-SNAPSHOT`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/1)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/archetypes/1#-KTx_qRdClb3O4GTk0fn:-KTxsN2PY_wXuuirwhFW:bdvjx1s) (no related file):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> Where would you use that property? To define the parent artifact using a variable which comes from the parent artifact? The `<version>` tags in the poms are probably unnecessary but they need to refer to the parent POM using `7.7-SNAPSHOT`
</details>
Either remove the `<version>` from each submodule and it automatically works as`<version>${project.parent.version}</version>` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/1)*

**Comment by Artur-** [comment]
Review status: 1 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/archetypes/1#-KTx_qRdClb3O4GTk0fn:-KTxwBYZsXOkJ7kq-sNq:b-s1irxz) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary>
> Either remove the `<version>` from each submodule and it automatically works as`<version>${project.parent.version}</version>` ?
</details>
Removed extra `<version>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/1)*

**Comment by pleku** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/archetypes/1)*

**Pull request merged**
